title: Munjarin Rahman
#logo: /Users/munjarinrahman/Downloads/OneDrive_1_05-02-2024/Linkedin Photos/DSC06914.JPG
description: Entrepreneur and Data Scientist
show_downloads: true
theme: jekyll-theme-minimal
